---
# Keep in mind....Vagrant will always create an initial interface as a NAT interface..Any definitions below are for adding additional interfaces.
# for network_name define a var other than remaining blank to define an internal only network. Otherwise leave blank for a host-only network.
# for DHCP leave ip and network_name vars blank
# for Static define ip var
# type should generally be private_network..Other option(s) are: public_network

virt:
  box: peru/ubuntu-20.04-server-amd64

env_common:
  assets: /tmp/assets
  domain: .example.com
  datadisk: /dev/vdb

services:
  nexus:
    ip: 192.168.122.100
    ports:
      apt:        8081
      dockerhub:  5000
  keepalived:
    vip: 192.168.123.100
    router-id: 51
  glusterfs:
    volname: gfs-docker
    volpath: /data/gluster/volume1
    mntpath: /data/docker-volumes
nodes:
  - name: edge0
    host: cc
    type: init
    mem: 2048
    cpus: 2
    interfaces:  #Define additional interface settings
      - ip: 192.168.122.200
        auto_config: "True"
        network_name: repo-net
        method: static
        type: private_network
      - ip: 192.168.123.10
        auto_config: "True"
        network_name: swarm-net
        method: static
        type: private_network
    keepalived:
      state: MASTER
      prio: 100

  - name: edge1
    host: cc
    type: manager
    mem: 2048
    cpus: 2
    interfaces:  #Define additional interface settings
      - ip: 192.168.122.201
        auto_config: "True"
        network_name: repo-net
        method: static
        type: private_network
      - ip: 192.168.123.11
        auto_config: "True"
        network_name: swarm-net
        method: static
        type: private_network
    keepalived:
      state: BACKUP
      prio: 99

  - name: edge2
    host: cc
    type: manager
    mem: 2048
    cpus: 2
    interfaces:  #Define additional interface settings
      - ip: 192.168.122.202
        auto_config: "True"
        network_name: repo-net
        method: static
        type: private_network
      - ip: 192.168.123.12
        auto_config: "True"
        network_name: swarm-net
        method: static
        type: private_network
    keepalived:
      state: BACKUP
      prio: 98

  - name: edge3
    host: cc
    type: worker
    mem: 2048
    cpus: 2
    interfaces:  #Define additional interface settings
      - ip: 192.168.122.203
        auto_config: "True"
        network_name: repo-net
        method: static
        type: private_network
      - ip: 192.168.123.13
        auto_config: "True"
        network_name: swarm-net
        method: static
        type: private_network
    keepalived:
      state: BACKUP
      prio: 50